### PR TITLE
Multiple views

### PR DESCRIPTION
**Pull request by damian66**
TODO list that i would like to add in the future:
- Changelog
- Change base branch from master to develop
- Add docs to list changes from the original version

### CODE REVIEW

**Comment by mrlubos** [comment]
Is this the one that will allow us to use a single instance to display both front and side view in the extractor?

**Comment by damian66** [comment]
@mrlubos yes, this is not ready for review as this is quite complex. And also I am working on other things and in free time jumping on this task. Most of the things I keep on my local machine - just wanted to see the changes I made some time ago.

**Comment by mrlubos** [comment]
@damian66 Excited for this one!

**Review by mrlubos — APPROVED** [review]
Approving, but not endorsing 🥴

**Pull request merged**
